services:
  - type: web
    name: piccola-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DDL_AUTO
        value: update
      - key: SHOW_SQL
        value: false
      - key: LOG_LEVEL
        value: INFO
      # Railway MySQL variables (configurar manualmente en Render)
      - key: MYSQLHOST
        value: yamanote.proxy.rlwy.net
      - key: MYSQLPORT
        value: 28411
      - key: MYSQLDATABASE
        value: railway
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: pFdxybzAvYZDjdvsIyURmKakkWKycbQE
